data/com.github.spheras.desktopfolder.appdata.xml

Improved the AppCenter listing. Additionally, the list of features was made more concise.

Improve AppCenter listing

---

po/fr.po
po/fr_FR.po

French translation based on original .pot file.
It looks like some strings are not properly managed, which results in incomplete translation. See attached capture for details.

French translation

---

src/utils/Util.vala

- Check for existing files (shows dialog on error) (#45)

Check for existing files

---

src/logic/FolderManager.vala
src/logic/NoteManager.vala
src/utils/Util.vala
src/widgets/FolderWindow.vala

- Fix #29 (and strip trailing and leading spaces from names)
- Add two error types to handle file errors

Add naming checks

---

arch/PKGBUILD

If you want to, you can add Arch support by just pushing this to the AUR

created PKGBUILD for Arch Linux packaging

---

po/sr.po

Update:Serbian translations

---

po/ru.po

Hi there,
I've updated Russian translation, fixed a couple of typos and improved it a bit. Feel free to merge it with the main branch.

Improved and updated Russian translation.

---

src/LanguageText.vala
src/dialogs/PanelPropertiesWindow.vala
src/logic/ItemManager.vala
src/widgets/ItemView.vala

To improve usability as a replacement for the traditional desktop, added an option to "Open with".

Added right-click "Open with other application" to file menu

---

src/LanguageText.vala
src/logic/FolderManager.vala
src/widgets/DesktopWindow.vala
src/widgets/FolderWindow.vala

Renewed PR, Added right-click option "Open terminal here", which is available on both the desktop and on panels.

Menuiten open terminal here

---

src/utils/EditableLabel.vala

Select text in entries when renaming

---

src/Application.vala
src/widgets/ItemView.vala

Show pointer cursor when hovering over icons when single click enabled

---

src/widgets/FolderWindow.vala

Small improvement to the input key logic (less branch depth).

Improve input key logic

---

src/LanguageText.vala
src/dialogs/PanelPropertiesWindow.vala

Properties Panel preview:
(I based it on the `feature-automaticarrange` branch so that's why this pull request is targeting that branch.)

Improvements to text wording and properties panel

---

src/Application.vala

Before this change it was syncing 4 times when notes or photos changed, now it only does it once.

Sync only once when notes or photos change

---

src/widgets/ItemView.vala

Add Ctrl detection to single click in ItemView on_release

---

src/utils/Util.vala
src/widgets/DesktopWindow.vala
src/widgets/FolderWindow.vala
src/widgets/NoteWindow.vala
src/widgets/PhotoWindow.vala

Position new windows where you initially right click

---

src/LanguageText.vala
src/dialogs/PanelPropertiesWindow.vala
src/logic/FolderManager.vala
src/logic/folderarrangement/FolderArrangement.vala
src/logic/folderarrangement/FolderArrangementFree.vala
src/logic/folderarrangement/FolderArrangementGrid.vala
src/logic/folderarrangement/FolderArrangementManaged.vala
src/utils/Util.vala
src/utils/dragndrop/DragNDrop.vala
src/widgets/DesktopWindow.vala
src/widgets/FolderWindow.vala
src/widgets/ItemView.vala

Reverts spheras/desktopfolder#189

Revert "Small improvements and cleanups"

---

src/LanguageText.vala
src/dialogs/PanelPropertiesWindow.vala
src/logic/FolderManager.vala
src/logic/folderarrangement/FolderArrangement.vala
src/logic/folderarrangement/FolderArrangementFree.vala
src/logic/folderarrangement/FolderArrangementGrid.vala
src/logic/folderarrangement/FolderArrangementManaged.vala
src/utils/Util.vala
src/utils/dragndrop/DragNDrop.vala
src/widgets/DesktopWindow.vala
src/widgets/FolderWindow.vala
src/widgets/ItemView.vala

It's the same PR as the last one but with the fix for the free arrangement bug.

Mini improvements and cleanups (fixed)

---

src/dialogs/PanelPropertiesWindow.vala

Fixed the icon search on elementary.

Fixed icon search on elementary.

---

debian/control

This should resolve the travis build issue for PR #231

Add intltool as a build-dependency #231

---

src/logic/FolderManager.vala
src/widgets/FolderWindow.vala

Fix Error: Couldn't find the newly created folder's

Fix problem by creating new folders

---

po/eo.po
po/fr.po
po/hu.po
po/it.po
po/pt_BR.po
po/ru.po

Latest translations including the french merge request #263

Translations

---

po/ca.po
po/es.po
po/nl_NL.po

Please can I ask that you make a new release soonest?  I would like to get the latest work into Debian and Ubuntu 20.04LTS.  TIA.

Latest translations

---

src/Application.vala

Closes #296 
Its more like workaround but at least it gets the job done. I had to add a workspace change listener and re-create desktop view. I'll investigate the issue more but for now, I think it's ok.

Missing desktop when workspace changed

---

src/Application.vala

Reverts spheras/desktopfolder#299

Revert "Missing desktop when workspace changed"
