- src/Application.vala
- src/LanguageText.vala
- src/Resources.vala
- src/logic/FolderManager.vala
- src/logic/ItemManager.vala
- src/logic/NoteManager.vala
- src/logic/PhotoManager.vala
- src/settings/FolderSettings.vala
- src/settings/ItemSettings.vala
- src/settings/NoteSettings.vala
- src/settings/PhotoSettings.vala
- src/uncrustify-elementary-vala.cfg
- src/utils/RenameDialog.vala
- src/utils/Util.vala
- src/widgets/FolderWindow.vala
- src/widgets/ItemView.vala
- src/widgets/NoteWindow.vala
- src/widgets/PhotoWindow.vala
- src/widgets/ProgressDialog.vala
- Ran clean up script on code (based on [elementary's code style guidelines](https://elementary.io/docs/code/reference#code-style)).
- Made some manual formatting edits
- Slightly edited one or two comments
- Corrected `clean_shortchut ()` to `clean_shortcut ()`
- (Panels and Notes) Renamed `delete ()` to `trash ()` which is what it actually does (`delete ()` is to be added)
- (Photos) Made PhotoManager `delete ()` actually delete the .dfp file (it's easy to add the photo back onto the desktop).
- Lessened repetition of `on_key` event in FolderWindow
- Added `trash ()` to ItemView which simply forwards to the ItemManager's `trash ()`
The large majority of the line changes are from the code formatting script.
This will probably not merge nicely with any other changes or branches because of …
> Code formatting clean up + minor edits

- data/css/Application.css
- src/LanguageText.vala
- src/widgets/FolderWindow.vala
- src/widgets/NoteWindow.vala
- Modify hover effect opacity slightly, it's more subtle now:
- Added the button hover effect to notes.
- Added `icon-shadow: none;` to headerbar button CSS to fix this when text shadow is disabled and window is active:
- Tidied up the FolderWindow context menu function. I sorted the parts into sections, gave the variables unique names and compacted the events to one line. I removed all the `.show ()`'s because `context_menu.show_all ()` does that for you.
- Edited some comments and fixed some grammar/typos. I also removed some comments because I thought some parts of the code are self explanatory, e.g.:
```vala
// The header bar		
var headerbar = new Gtk.HeaderBar ();
```
- Changed align to grid sensitivity from `101` to `100` which stops the icons from slightly shifting when the grid is …
> Change header button hover effect (and minor code clean ups)

- src/settings/PhotoSettings.vala
- src/utils/Util.vala
- Fixes segmentation fault from unset variables
- Prevents creating an invalid photo in the first place
This doesn't fix the fact that PhotoSettings isn't checked at all if it returns `null`.
> Fix segmentation fault

- README.md
> Add libjson-glib-dev to dependency list in README

- data/com.github.spheras.desktopfolder.gschema.xml
- src/Application.vala
from #119 
Allow the ability to override the initial first folder
created when desktopfolder is first run
> Add first-folder schema settings

- data/com.github.spheras.desktopfolder.gschema.xml
- src/Application.vala
this PR resolves #126 
Simple test:
1. check that the default install, desktopfolder starts up ok ---> yes it does
2. Toggle off the new schema key when desktopfolder is running --> desktopfolder quits without error on the command line
3. Start desktopfolder when the new schema key is toggled off --> desktopfolder immediately quits without error.
> Allow desktop configuration apps to stop showing desktopfolder #126

- data/com.github.spheras.desktopfolder.appdata.xml
- src/logic/NoteManager.vala
- src/logic/PhotoManager.vala
- src/settings/FolderSettings.vala
- src/utils/dragndrop/DragNDrop.vala
This PR fixes a few things thrown up when running lintian on the built debian package (the typos).
Also, when running check-all-the-things, it raised a few `appstreamcli validate` issues (version found in 18.10).
Both are stuff that Debian would normally query as part of a new package upload and would likely ask to be resolved.  Hence this PR.
> Typos and appstream validation issues

- src/widgets/ItemView.vala
This should resolve the above (#135) issue.
Tested with a .desktop file with
1. a full path to a .svg, 
2. an icon-name that corresponded to a svg
3. a full path to a random .png
4. an icon-name that corresponded to a png
Then for the choose icon dialog I browsed to a .svg and selected it.  This changed the icon to the svg.
I restarted desktopfolder and the changed icons were remembered.
> Full path icon display and SVG choose icon support #135

- src/LanguageText.vala
- src/logic/FolderManager.vala
- src/logic/ItemManager.vala
- src/widgets/ItemView.vala
An extension of the previous "Open terminal here" right-click option. This one adds a conditional menu item (if the item is a folder): "Open in terminal".
> Open folder in terminal

- snap/snapcraft.yaml
I have had a go tidying up the snap.
It now builds and runs ... sort of ...
It saves the desktop results within the snap itself - i.e. doesnt display the contents of ~/Desktop
It doesnt open a terminal - suspect I am missing a stage-package complaining that it can't execute the child process x-terminal-emulator
But from a quick glance, you can create panels, files, link files, photos
So this is at least something someone can work with to cleanup and fixup
> Cleanup and build with new core18 and gnome-3.28 platform

- src/LanguageText.vala
- src/logic/FolderManager.vala
- src/settings/FolderSettings.vala
- src/settings/NoteSettings.vala
- src/utils/Util.vala
- src/widgets/FolderWindow.vala
- src/widgets/NoteWindow.vala
Fixes #162 
- Instead of showing the naming dialog, the application now creates panels, notes and files/folders and automatically triggers the editing of the label.
- Duplicate naming is handled.
- Copy and paste a file in the same directory will now create a copy (uses same duplicate naming function).
- Misc additional fixes and typo corrections.
Problems:
- Is FolderManager's new function `get_item_by_filename` a suitable way of doing what I intended to do or is there a better way?
- The triggering of the editable label for notes isn't working quite correctly. I'm not sure what is causing it.
> Replace naming dialogs with rename in place

- src/LanguageText.vala
- src/dialogs/PanelPropertiesWindow.vala
- src/logic/FolderManager.vala
- src/logic/folderarrangement/FolderArrangement.vala
- src/logic/folderarrangement/FolderArrangementFree.vala
- src/logic/folderarrangement/FolderArrangementGrid.vala
- src/logic/folderarrangement/FolderArrangementManaged.vala
- src/utils/Util.vala
- src/utils/dragndrop/DragNDrop.vala
- src/widgets/DesktopWindow.vala
- src/widgets/FolderWindow.vala
- src/widgets/ItemView.vala
- Reorganise desktop context menu a bit
- Fix doubling of "When changing resolution" label
- Change label text slightly
- Remove hint for "default icon arrangement" because I think the label is enough to understand what it does
- Don't show "lock panel" for the desktop panel in panel properties because it does nothing
- Drag and drop when items are locked
- Copying a folder into the same parent folder now duplicates like files
- Don't create a link if the target file/folder already exists (if the target was a folder it was creating a link in there)
- Fix icon context menu trash label saying "Delete"
- Fix #192
> Small improvements and cleanups

- src/LanguageText.vala
- src/dialogs/PanelPropertiesWindow.vala
- Improve wording
- Use Gtk.SpinButton instead
- Put general icon settings into it's own section
Screenshots:
> Tweak panel properties

- src/LanguageText.vala
- src/dialogs/PanelPropertiesWindow.vala
- src/logic/ItemManager.vala
- src/widgets/ItemView.vala
Additional right-click option: 
- Suggest considering to move the set-icon option to this properties window, similar to how nautilus handles it. 
- Also: the source file  `PanelPropertiesWindow.vala` might have a confusing name after the latest additions. Suggest renaming it to `DesktopFolderDialogs.vala` or something like that.
> Added right-click -> show properties.

- src/Application.vala
- src/settings/PositionSettings.vala
- src/utils/dragndrop/DndBehaviour.vala
- src/utils/dragndrop/DragNDrop.vala
Disco (proposed) has upgraded to vala 0.44 and desktopfolder v1.0.10 no longer builds
Ubuntu Devs have created a patch for that particular version to get it to build under vala 0.44.
This PR is based on that patch rebased for v1.1.0.
So this resolves the compilation issues.
However - important - this just gets the compilation working.  I'm unsure that the changes meet the intention of what the code was originally doing, so please review carefully and advise.
> Fix compilation issues with vala 0.44

- data/com.github.spheras.desktopfolder.desktop.in
gnome-settings-daemon has the ability to start/stop desktopfolder depending upon the value of a gsettings key.
This PR connects to desktopfolders show-desktop key so that desktops such as budgie can switch desktopfolder on/off
> Let GSD handle starting/not starting desktopfolder via autostart

- src/logic/PhotoManager.vala
- src/widgets/PhotoWindow.vala
from #277 
This adds a right click option to the photo right click popup to open the photo in the default viewer.
Also called the same routine via a double click on the photo itself
> Add popup option to open photo in default viewer

- src/LanguageText.vala
- src/utils/menu/MenuItemColor.vala
- src/widgets/DesktopWindow.vala
- src/widgets/FolderWindow.vala
- src/widgets/NoteWindow.vala
- src/widgets/PhotoWindow.vala
This PR tidies the right click menu to have "actions" together.
This I feel is more logical - ensures the colours option remains at the bottom to be consistent with other popups and also ensures the previous number of menu separators dont excessively enlarge the menu popup improving its appearance
I've also fixed the padding issue for the custom menuitemcolor so that it is under the text for all themes.  This was tested with a variety of themes to ensure it worked.
I've fixed a crasher for the color dialog on first use.
> Reorganise menu to combine actions

- src/utils/animation/GtkAnimation.vala
In Vala 0.45+, abstract classes can no longer have creation methods which are public. Changing it to protected so it may also be used by sub-classes resolves this issue.
> Fix compilation against Vala 0.46

- data/css/Application.css
This is a proposed fix for issue #297  . The wallpaper is shown as black seemingly due to an underlying element on top of the wallpaper itself. I didn't go through debugging how come this element exists and wasn't styled -- it doesn't look like there should be an element from the code in the first place -- and since the issue only affects certain distros, I thought a styling workaround would be a good approach.
In short, the styling workaround forces transparency on any descendant of a transparent folder if it doesn't have a styled background.
I tested on my machine, Fedora 32, and the fix looks fine.
> Fix the bug of blacked wallpaper on some Linux distros.
